# Generated by Django 3.2.8 on 2021-10-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211021_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
