# Generated by Django 3.2.8 on 2021-10-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20211030_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='product_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user_comment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='product_item',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_watchlist',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
